name: salem_portfolio
description: "my portfolio."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gradient_borders: ^1.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/poppins/
    - assets/icons/
    - assets/projects/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 900



flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
#    flare_flutter: false
    rive: false
    lottie: false

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/app_iconss.png"
    background_color: "#C10055"
    theme_color: "#C10055"
  windows:
    generate: true
    image_path: "assets/app_iconss.png"
    icon_size: 48 # min:48, max:256, default: 48
